id: IC4410505
legacy_id: P008085
ocr_import_info:
  bdrc_scan_id: W1KG14641
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:47:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T07:04:41.416780+00:00'
last_modified: 2022-08-31 15:04:59.367809
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14641
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14641
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ།
  author: ཐར་ཤུལ ༠༤་དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.562718276507019
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I1KG14645:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14645
      total_pages: 623
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG14645.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.562718276507019
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
