id: P008085
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14641
  title: གསུང་འབུམ། དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ།
  author: ''
  volumes:
    f53f886c4f0640979fb377b4f2c82210:
      image_group_id: I1KG14645
      title: ''
      volume_number: 1
      total_pages: 623
ebook_metadata:
  title: གསུང་འབུམ། དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ།
  author: ''
  sku: P008085
  cover: cover.jpg
  layers:
  - pagination
